### ISSUE TITLE
installation of apiban-mysql fails

### ISSUE THREAD

**Issue by bferrell** [ajamous/apiban-mysql#1]
npm install 
apiban_banned_ips@1.0.0 /usr/local/src/voip/apiban-mysql
├─┬ bent@7.3.12 
│ ├── bytesish@0.4.4 
│ ├── caseless@0.12.0 
│ └── is-stream@2.0.1 
├─┬ mysql2@2.3.3 
│ ├── denque@2.1.0 
│ ├─┬ generate-function@2.3.1 
│ │ └── is-property@1.0.2 
│ ├─┬ iconv-lite@0.6.3 
│ │ └── safer-buffer@2.1.2 
│ ├── long@4.0.0 
│ ├─┬ lru-cache@6.0.0 
│ │ └── yallist@4.0.0 
│ ├─┬ named-placeholders@1.1.2 
│ │ └─┬ lru-cache@4.1.5 
│ │   ├── pseudomap@1.0.2 
│ │   └── yallist@2.1.2 
│ ├── seq-queue@0.0.5 
│ └── sqlstring@2.3.3 
└─┬ util@0.12.5 
  ├── inherits@2.0.4 
  ├─┬ is-arguments@1.1.1 
  │ ├─┬ call-bind@1.0.2 
  │ │ ├── function-bind@1.1.1 
  │ │ └─┬ get-intrinsic@1.1.3 
  │ │   └── has@1.0.3 
  │ └─┬ has-tostringtag@1.0.0 
  │   └── has-symbols@1.0.3 
  ├── is-generator-function@1.0.10 
  ├─┬ is-typed-array@1.1.10 
  │ ├── available-typed-arrays@1.0.5 
  │ ├─┬ for-each@0.3.3 
  │ │ └── is-callable@1.2.7 
  │ └── gopd@1.0.1 
  └── which-typed-array@1.1.9 

npm WARN apiban_banned_ips@1.0.0 No repository field.

**Comment by ajamous** [comment]
Thank you for reporting this. 

I have updated the package.json file to include the "repository" field. @bferrell , can you please verify if there are still any issues?

**Comment by bferrell** [comment]
install completes

node sync.js 
/usr/local/src/voip/apiban-mysql/sync.js:47
const getBlacklist = async() => {
                          ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

**Comment by telecomsxchange** [comment]
@bferrell can you please share the version of Nodejs you're running ?

**Comment by bferrell** [comment]
node --version
v6.17.1

**Comment by telecomsxchange** [comment]
@bferrell the solution would be to ensure that you are running the script with a version of Node.js that supports the async keyword. Updating the Node.js version to the latest one should solve the problem.
